### ISSUE TITLE
ImportError: cannot import name 'scene'

### ISSUE THREAD

**Issue by KunFang93** [alejandrobll/py-sphviewer#28]
Hi,

I am a new user of this useful package~ I installed it by command   
```
conda install -c alejandrobll py-sphviewer
```
I meet the following error message  
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/KunFang/anaconda/envs/py-sphviewer/lib/python3.6/site-packages/sphviewer/Scene.py", line 114, in __init__
    self._x, self._y, self._hsml, self._kview = self.__compute_scene()
  File "/Users/KunFang/anaconda/envs/py-sphviewer/lib/python3.6/site-packages/sphviewer/Scene.py", line 160, in __compute_scene
    from .extensions import scene
ImportError: cannot import name 'scene'
```
when I tried to run codes:  
```
x = np.random.randn(1000)
y = np.random.randn(1000)
xmin = np.min(x)
xmax = np.max(x)
ymin = np.min(y)
ymax = np.max(y)
x0 = (xmin+xmax)/2.
y0 = (ymin+ymax)/2.
pos = np.zeros([len(x),3])
pos[:,0] = x
pos[:,1] = y
w = np.ones(len(x))
P = sph.Particles(pos, w, nb=32)
```

I was wondering if there is anyway to solve it, thanks!

Kun

**Comment by alejandrobll** [comment]
This seems related to your local configuration. I would advice installing in a fresh environment using pip. The conda repository is currently outdated.

**Comment by KunFang93** [comment]
Thanks for your reply! I tried to install sphviewer with pip but encounter the following error:
```
ERROR: Command errored out with exit status 1:
   command: /Users/KunFang/anaconda/envs/py-sphviewer/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7n/k0q2cb_521b66_14fhq8hjrm0000gn/T/pip-install-48uivrr3/py-sphviewer_1014c87f40be4876a061b7f3648324b5/setup.py'"'"'; __file__='"'"'/private/var/folders/7n/k0q2cb_521b66_14fhq8hjrm0000gn/T/pip-install-48uivrr3/py-sphviewer_1014c87f40be4876a061b7f3648324b5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/7n/k0q2cb_521b66_14fhq8hjrm0000gn/T/pip-wheel-ilqd75vb
       cwd: /private/var/folders/7n/k0q2cb_521b66_14fhq8hjrm0000gn/T/pip-install-48uivrr3/py-sphviewer_1014c87f40be4876a061b7f3648324b5/
  Complete output (44 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.6
  creating build/lib.macosx-10.9-x86_64-3.6/sphviewer
  copying sphviewer/version.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer
  copying sphviewer/Render.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer
  copying sphviewer/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer
  copying sphviewer/Scene.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer
  copying sphviewer/Particles.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer
  copying sphviewer/Camera.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer
  creating build/lib.macosx-10.9-x86_64-3.6/sphviewer/extensions
  copying sphviewer/extensions/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer/extensions
  creating build/lib.macosx-10.9-x86_64-3.6/sphviewer/tools
  copying sphviewer/tools/Blend.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer/tools
  copying sphviewer/tools/hsv_tools.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer/tools
  copying sphviewer/tools/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer/tools
  copying sphviewer/tools/QuickView.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer/tools
  copying sphviewer/tools/camera_tools.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer/tools
  copying sphviewer/tools/cmaps.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer/tools
  copying sphviewer/extra_code.c -> build/lib.macosx-10.9-x86_64-3.6/sphviewer
  copying sphviewer/c_code.c -> build/lib.macosx-10.9-x86_64-3.6/sphviewer
  copying sphviewer/README.txt -> build/lib.macosx-10.9-x86_64-3.6/sphviewer
  running build_ext
  creating var
  creating var/folders
  creating var/folders/7n
  creating var/folders/7n/k0q2cb_521b66_14fhq8hjrm0000gn
  creating var/folders/7n/k0q2cb_521b66_14fhq8hjrm0000gn/T
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/KunFang/anaconda/envs/py-sphviewer/include -arch x86_64 -I/Users/KunFang/anaconda/envs/py-sphviewer/include -arch x86_64 -I/Users/KunFang/anaconda/envs/py-sphviewer/lib/python3.6/site-packages/numpy/core/include -I/Users/KunFang/anaconda/envs/py-sphviewer/include/python3.6m -c /var/folders/7n/k0q2cb_521b66_14fhq8hjrm0000gn/T/tmp_qj80wh4.c -o var/folders/7n/k0q2cb_521b66_14fhq8hjrm0000gn/T/tmp_qj80wh4.o -fopenmp
  clang: error: unsupported option '-fopenmp'
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/KunFang/anaconda/envs/py-sphviewer/include -arch x86_64 -I/Users/KunFang/anaconda/envs/py-sphviewer/include -arch x86_64 -I/Users/KunFang/anaconda/envs/py-sphviewer/lib/python3.6/site-packages/numpy/core/include -I/Users/KunFang/anaconda/envs/py-sphviewer/include/python3.6m -c /var/folders/7n/k0q2cb_521b66_14fhq8hjrm0000gn/T/tmp4b3bip0e.c -o var/folders/7n/k0q2cb_521b66_14fhq8hjrm0000gn/T/tmp4b3bip0e.o -Xpreprocessor -fopenmp -lomp
  clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
  building 'sphviewer/extensions/scene' extension
  creating build/temp.macosx-10.9-x86_64-3.6
  creating build/temp.macosx-10.9-x86_64-3.6/sphviewer
  creating build/temp.macosx-10.9-x86_64-3.6/sphviewer/extensions
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/KunFang/anaconda/envs/py-sphviewer/include -arch x86_64 -I/Users/KunFang/anaconda/envs/py-sphviewer/include -arch x86_64 -I/Users/KunFang/anaconda/envs/py-sphviewer/lib/python3.6/site-packages/numpy/core/include -I/Users/KunFang/anaconda/envs/py-sphviewer/include/python3.6m -c sphviewer/extensions/scenemodule.c -o build/temp.macosx-10.9-x86_64-3.6/sphviewer/extensions/scenemodule.o -std=c99 -w -ffast-math -I/Users/KunFang/anaconda/envs/py-sphviewer/lib/python3.6/site-packages/numpy/core/include -Xpreprocessor -fopenmp -lomp
  sphviewer/extensions/scenemodule.c:26:10: fatal error: 'omp.h' file not found
  #include <omp.h>
           ^~~~~~~
  1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for py-sphviewer
  Running setup.py clean for py-sphviewer
Failed to build py-sphviewer
Installing collected packages: python-dateutil, pyparsing, pillow, kiwisolver, cycler, scipy, pykdtree, matplotlib, py-sphviewer
    Running setup.py install for py-sphviewer ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/KunFang/anaconda/envs/py-sphviewer/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7n/k0q2cb_521b66_14fhq8hjrm0000gn/T/pip-install-48uivrr3/py-sphviewer_1014c87f40be4876a061b7f3648324b5/setup.py'"'"'; __file__='"'"'/private/var/folders/7n/k0q2cb_521b66_14fhq8hjrm0000gn/T/pip-install-48uivrr3/py-sphviewer_1014c87f40be4876a061b7f3648324b5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/7n/k0q2cb_521b66_14fhq8hjrm0000gn/T/pip-record-m_wcpfky/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/KunFang/.local/include/python3.6m/py-sphviewer
         cwd: /private/var/folders/7n/k0q2cb_521b66_14fhq8hjrm0000gn/T/pip-install-48uivrr3/py-sphviewer_1014c87f40be4876a061b7f3648324b5/
    Complete output (39 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.6
    creating build/lib.macosx-10.9-x86_64-3.6/sphviewer
    copying sphviewer/version.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer
    copying sphviewer/Render.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer
    copying sphviewer/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer
    copying sphviewer/Scene.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer
    copying sphviewer/Particles.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer
    copying sphviewer/Camera.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer
    creating build/lib.macosx-10.9-x86_64-3.6/sphviewer/extensions
    copying sphviewer/extensions/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer/extensions
    creating build/lib.macosx-10.9-x86_64-3.6/sphviewer/tools
    copying sphviewer/tools/Blend.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer/tools
    copying sphviewer/tools/hsv_tools.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer/tools
    copying sphviewer/tools/__init__.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer/tools
    copying sphviewer/tools/QuickView.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer/tools
    copying sphviewer/tools/camera_tools.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer/tools
    copying sphviewer/tools/cmaps.py -> build/lib.macosx-10.9-x86_64-3.6/sphviewer/tools
    copying sphviewer/extra_code.c -> build/lib.macosx-10.9-x86_64-3.6/sphviewer
    copying sphviewer/c_code.c -> build/lib.macosx-10.9-x86_64-3.6/sphviewer
    copying sphviewer/README.txt -> build/lib.macosx-10.9-x86_64-3.6/sphviewer
    running build_ext
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/KunFang/anaconda/envs/py-sphviewer/include -arch x86_64 -I/Users/KunFang/anaconda/envs/py-sphviewer/include -arch x86_64 -I/Users/KunFang/anaconda/envs/py-sphviewer/lib/python3.6/site-packages/numpy/core/include -I/Users/KunFang/anaconda/envs/py-sphviewer/include/python3.6m -c /var/folders/7n/k0q2cb_521b66_14fhq8hjrm0000gn/T/tmpyuh4lphn.c -o var/folders/7n/k0q2cb_521b66_14fhq8hjrm0000gn/T/tmpyuh4lphn.o -fopenmp
    clang: error: unsupported option '-fopenmp'
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/KunFang/anaconda/envs/py-sphviewer/include -arch x86_64 -I/Users/KunFang/anaconda/envs/py-sphviewer/include -arch x86_64 -I/Users/KunFang/anaconda/envs/py-sphviewer/lib/python3.6/site-packages/numpy/core/include -I/Users/KunFang/anaconda/envs/py-sphviewer/include/python3.6m -c /var/folders/7n/k0q2cb_521b66_14fhq8hjrm0000gn/T/tmpgl_qn4do.c -o var/folders/7n/k0q2cb_521b66_14fhq8hjrm0000gn/T/tmpgl_qn4do.o -Xpreprocessor -fopenmp -lomp
    clang: warning: -lomp: 'linker' input unused [-Wunused-command-line-argument]
    building 'sphviewer/extensions/scene' extension
    creating build/temp.macosx-10.9-x86_64-3.6
    creating build/temp.macosx-10.9-x86_64-3.6/sphviewer
    creating build/temp.macosx-10.9-x86_64-3.6/sphviewer/extensions
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/KunFang/anaconda/envs/py-sphviewer/include -arch x86_64 -I/Users/KunFang/anaconda/envs/py-sphviewer/include -arch x86_64 -I/Users/KunFang/anaconda/envs/py-sphviewer/lib/python3.6/site-packages/numpy/core/include -I/Users/KunFang/anaconda/envs/py-sphviewer/include/python3.6m -c sphviewer/extensions/scenemodule.c -o build/temp.macosx-10.9-x86_64-3.6/sphviewer/extensions/scenemodule.o -std=c99 -w -ffast-math -I/Users/KunFang/anaconda/envs/py-sphviewer/lib/python3.6/site-packages/numpy/core/include -Xpreprocessor -fopenmp -lomp
    sphviewer/extensions/scenemodule.c:26:10: fatal error: 'omp.h' file not found
    #include <omp.h>
             ^~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/KunFang/anaconda/envs/py-sphviewer/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7n/k0q2cb_521b66_14fhq8hjrm0000gn/T/pip-install-48uivrr3/py-sphviewer_1014c87f40be4876a061b7f3648324b5/setup.py'"'"'; __file__='"'"'/private/var/folders/7n/k0q2cb_521b66_14fhq8hjrm0000gn/T/pip-install-48uivrr3/py-sphviewer_1014c87f40be4876a061b7f3648324b5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/7n/k0q2cb_521b66_14fhq8hjrm0000gn/T/pip-record-m_wcpfky/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/KunFang/.local/include/python3.6m/py-sphviewer Check the logs for full command output.
```
I checked my openmp and found it is already installed. And my gcc version is 'Apple clang version 11.0.3 (clang-1103.0.32.62)'. I was wondering if it is possible to solve this error? Thanks for your time!

Best,
Kun

**Comment by alejandrobll** [comment]
Your `OpenMP` header is missing, or not being seen by `gcc`. It is most likely located in a non-standard directory. I would locate the `omp.h` file and then follow the documentation [here](https://gcc.gnu.org/onlinedocs/gcc/Environment-Variables.html). In particular, the section about `CPATH`. You can define this environment variable and include the directory that contains `omp.h` before executing `pip install`.
